require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CaartsController do

  # This should return the minimal set of attributes required to create a valid
  # Caart. As you add validations to Caart, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CaartsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all caarts as @caarts" do
      caart = Caart.create! valid_attributes
      get :index, {}, valid_session
      assigns(:caarts).should eq([caart])
    end
  end

  describe "GET show" do
    it "assigns the requested caart as @caart" do
      caart = Caart.create! valid_attributes
      get :show, {:id => caart.to_param}, valid_session
      assigns(:caart).should eq(caart)
    end
  end

  describe "GET new" do
    it "assigns a new caart as @caart" do
      get :new, {}, valid_session
      assigns(:caart).should be_a_new(Caart)
    end
  end

  describe "GET edit" do
    it "assigns the requested caart as @caart" do
      caart = Caart.create! valid_attributes
      get :edit, {:id => caart.to_param}, valid_session
      assigns(:caart).should eq(caart)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Caart" do
        expect {
          post :create, {:caart => valid_attributes}, valid_session
        }.to change(Caart, :count).by(1)
      end

      it "assigns a newly created caart as @caart" do
        post :create, {:caart => valid_attributes}, valid_session
        assigns(:caart).should be_a(Caart)
        assigns(:caart).should be_persisted
      end

      it "redirects to the created caart" do
        post :create, {:caart => valid_attributes}, valid_session
        response.should redirect_to(Caart.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved caart as @caart" do
        # Trigger the behavior that occurs when invalid params are submitted
        Caart.any_instance.stub(:save).and_return(false)
        post :create, {:caart => {  }}, valid_session
        assigns(:caart).should be_a_new(Caart)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Caart.any_instance.stub(:save).and_return(false)
        post :create, {:caart => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested caart" do
        caart = Caart.create! valid_attributes
        # Assuming there are no other caarts in the database, this
        # specifies that the Caart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Caart.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => caart.to_param, :caart => { "these" => "params" }}, valid_session
      end

      it "assigns the requested caart as @caart" do
        caart = Caart.create! valid_attributes
        put :update, {:id => caart.to_param, :caart => valid_attributes}, valid_session
        assigns(:caart).should eq(caart)
      end

      it "redirects to the caart" do
        caart = Caart.create! valid_attributes
        put :update, {:id => caart.to_param, :caart => valid_attributes}, valid_session
        response.should redirect_to(caart)
      end
    end

    describe "with invalid params" do
      it "assigns the caart as @caart" do
        caart = Caart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Caart.any_instance.stub(:save).and_return(false)
        put :update, {:id => caart.to_param, :caart => {  }}, valid_session
        assigns(:caart).should eq(caart)
      end

      it "re-renders the 'edit' template" do
        caart = Caart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Caart.any_instance.stub(:save).and_return(false)
        put :update, {:id => caart.to_param, :caart => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested caart" do
      caart = Caart.create! valid_attributes
      expect {
        delete :destroy, {:id => caart.to_param}, valid_session
      }.to change(Caart, :count).by(-1)
    end

    it "redirects to the caarts list" do
      caart = Caart.create! valid_attributes
      delete :destroy, {:id => caart.to_param}, valid_session
      response.should redirect_to(caarts_url)
    end
  end

end
